apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: owm7tl27r-nodejs
  janus-idp.io/tekton: owm7tl27r-nodejs
  backstage.io/kubernetes-id: owm7tl27r-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: owm7tl27r-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
